// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rarhqnvvbjzfdevnghnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhcmhxbnZ2Ymp6ZmRldm5naG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NzYwNzgsImV4cCI6MjA2NzQ1MjA3OH0.yvG3MIFbssrNa8wl5qFBi5NWBgZq0gmy8Ovc3yGoliY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Verrou auth résilient: le verrou natif (navigator.locks) peut rester bloqué
// en WebView / multi-onglets, ce qui fait stagner getSession() et provoque des
// "déconnexions/reconnexions" intempestives. On tente le verrou natif avec un
// délai max, puis on exécute quand même l'opération pour éviter tout blocage.
const resilientLock = async <R>(
  name: string,
  acquireTimeout: number,
  fn: () => Promise<R>,
): Promise<R> => {
  const navLocks = (globalThis as any)?.navigator?.locks;
  if (!navLocks?.request) {
    return await fn();
  }

  try {
    return await navLocks.request(
      name,
      { mode: 'exclusive', ifAvailable: false },
      async () => {
        // Garde-fou: ne jamais laisser l'opération bloquer indéfiniment.
        return await Promise.race([
          fn(),
          new Promise<R>((_, reject) =>
            setTimeout(() => reject(new Error('auth-lock-fn-timeout')), 8000),
          ),
        ]);
      },
    );
  } catch {
    // Verrou indisponible ou expiré: on exécute sans verrou plutôt que stagner.
    return await fn();
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    lock: resilientLock,
  },
  global: {
    headers: {
      'x-client-info': 'nettobloc-app',
    },
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});
